directories:
  output: './output'
  flattened_output: './flattened_output'
  excel_output: './excel_output'

autodoc_template_path: './autodoc_template.docx'
autodoc_completed_path: './autodoc_completed.docx'
autodoc_completed_path_with_bios: './autodoc_completed_with_bios.docx'
base_url: 'https://www.intersight.com/api/v1/'


CUSTOMER_INFO:
 - customer_name: 'Customer Name'
 - date: 'Day Month Year'